# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update angular

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run ng update;
    - run: yarn run ng update @angular/core @angular/cli @angular/cdk @angular/material @angular/localize;
    - run: git config user.name "Linus Torvalds";
      if: always()
    - run: git config user.email "torvalds@linux-foundation.org";
      if: always()
    - run: git add .;
      if: always()
    - run: git commit -m "update angular" -m "angular {cli, cdk, material, localize}, and rxjs";
      if: always()
    - run: git pull --rebase --strategy-option=theirs;
      if: always()
    - run: git push origin master;
      if: always()
